###############################################################################
# Copyright (c) 2022 CEA
# This program and the accompanying materials are made available under the 
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-License-Identifier: EPL-2.0
# Contributors: see AUTHORS file
###############################################################################

site_name: NabLab documentation
site_url: https://cea-hpc.github.io/NabLab
site_description: This is the documentation website of NabLab project
site_author: Benoit Lelandais
copyright: Copyright &copy; 2022 CEA

nav:
  - What is NabLab: index.md
  - Getting started: gettingstarted.md
  - My first module: firstmodule.md
  - My first extension: firstextension.md
  - Composing modules: modulecomposition.md
  - Monitoring and debugging: debug.md
  - NabLab language reference: nablablanguage.md
  - Ngen language reference: ngenlanguage.md
  - Docker integration: docker.md 
  - Arcane code generation: arcane.md

theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: default
    primary: indigo
    accent: orange
  features:
    - navigation.instant
  favicon: img/logo_512.png
  logo: img/logo_512.png

# for LaTeX
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra:
  version: 0.4.0
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/cea-hpc/NabLab'

